# Generated by Django 5.1.7 on 2025-03-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=255)),
                ('instance', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('revision', models.PositiveIntegerField()),
                ('language_code', models.CharField(max_length=7)),
                ('answer_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of when the user answered this exercise')),
                ('answerer_ip', models.GenericIPAddressField()),
                ('task_id', models.CharField(blank=True, max_length=36, null=True)),
                ('collaborators', models.TextField(blank=True, null=True, verbose_name='Which users was this exercise answered with')),
                ('checked', models.BooleanField(default=False, verbose_name='This answer has been checked')),
                ('draft', models.BooleanField(default=False, verbose_name='This answer is a draft')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluation.evaluation')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UserMultipleChoiceExerciseAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_answer.useranswer')),
                ('chosen_answer', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_answer.useranswer',),
        ),
        migrations.CreateModel(
            name='UserTextfieldExerciseAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_answer.useranswer')),
                ('given_answer', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_answer.useranswer',),
        ),
    ]
