# Generated by Django 5.1.7 on 2025-03-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMultipleQuestionExamAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_answer.useranswer')),
                ('attempt', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_answer.useranswer',),
        ),
    ]
