# Generated by Django 5.1.7 on 2025-04-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_answer', '0002_usermultiplequestionexamanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckboxExerciseAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_answer.useranswer')),
                ('chosen_answers', models.JSONField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_answer.useranswer',),
        ),
    ]
