# Generated by Django 5.1.7 on 2025-04-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_answer", "0004_alter_useranswer_evaluation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="collaborators",
        ),
    ]
